### ISSUE TITLE
Errors in geom_lm() due to missing years

### ISSUE THREAD

**Issue by kimberly-bastille** [andybeet/arfit#2]
Error message below comes up in plots with indicators with missing 2020 data point. 

` Error in optim(par = rho, fn = likelihood_ar1, gr = NULL, data, hypothesis,  : 
 L-BFGS-B needs finite values of 'fn'`
 
@andybeet  Does the analysis prevent us from running with missing data or is this just something we forgot to include in the code?

**Comment by andybeet** [comment]
I haven't coded for missing data yet. I need to do that.

**Comment by kimberly-bastille** [comment]
Let me know when that is in and I will bring it into ecodata. Thanks.

**Comment by kimberly-bastille** [comment]
I added a workaround solution to ecodata. I just commented out `#tidyr::complete(x = tidyr::full_seq(min(data$x):max(data$x),1)) %>%` (Line 22 in StatLM in ecodata). 

This removes the step that fills in time steps with NAs if there are missing years. This is not the correct way to handle missing years for this methodology. @andybeet Do you have a method for handling missing data?

**Comment by andybeet** [comment]
Not yet implemented this. Hope to get to it in next few months

**Comment by kimberly-bastille** [comment]
@andybeet Just a reminder.

**Comment by andybeet** [comment]
Fixed in [PR 5](https://github.com/andybeet/arfit/pull/5). Changes made in ecodata package to `geom_lm`, `GeomLM`, and `StatLM`
